Added connect models
blackout1471/H5_MQTT pull request #2
Opened 2022-08-18 11:08 UTC by Ripiter

2022-08-18 11:13 UTC, Geefy requested changes

2022-08-18 11:13 UTC, Geefy commented on Source/Models/MQTTModels/ConnetPacket.h
> +#include "ControllHeader.h"
Stavefejl

2022-08-18 11:13 UTC, Geefy commented on Source/Models/MQTTModels/ConnectPayload.h
> +		int16_t UsernameLenght;
Stavefejl

2022-08-18 11:13 UTC, Geefy commented on Source/Models/MQTTModels/ConnectPayload.h
> +		int16_t ClientIDLenght;
Stavefejl

2022-08-18 11:13 UTC, Geefy commented on Source/Models/MQTTModels/ConnectVariableHeader.h
> +namespace MQTTModels
Follow namespace from diagram

2022-08-18 11:13 UTC, Geefy commented on Source/Models/MQTTModels/ConnectVariableHeader.h
> +	enum ConnectFlag {
Own class

2022-08-18 11:13 UTC, Geefy commented on Source/Models/MQTTModels/ConnetPacket.h
> +	struct ConnectPacket
ConnectPackage

2022-08-18 11:13 UTC, Geefy commented on Source/Models/MQTTModels/ConnetPacket.h
> +		inline ControllHeader GetConnectControllHeader() { return m_controllHeader; }
mangler const reference og controll = control

2022-08-18 11:13 UTC, Geefy commented on Source/Models/MQTTModels/ControllHeader.h
> +		ControllFieldType PacketType;
Controll = control

2022-08-19 06:23 UTC, Geefy requested changes

2022-08-19 06:23 UTC, Geefy commented on Source/Models/MQTTModels/ConnetPackage.h
> +			inline const ControlHeader& GetConnectControllHeader() { return m_ControlHeader; }
Controll = Control

2022-08-19 06:23 UTC, Geefy commented on Source/Models/MQTTModels/ConnetPackage.h
> +			inline void SetConnectControllHeader(const ControlHeader& _controllHeader) { m_ControlHeader = _controllHeader; }
Controll = Control

2022-08-19 06:25 UTC, blackout1471 commented on Source/Models/MQTTModels/ConnectFlagType.h
> +		enum ConnectFlagType : int
The type should be unsigned char

2022-08-19 06:25 UTC, blackout1471 commented on Source/Models/MQTTModels/ConnectVariableHeader.h
> +		public:
Public not needed

2022-08-19 06:25 UTC, blackout1471 commented on Source/Models/MQTTModels/ControlHeader.h
> +		public:
Public not needed

2022-08-19 06:25 UTC, blackout1471 commented on Source/Models/MQTTModels/ControlPackageType.h
> +		enum ControlPackageType : int
Type should be unsigned char

2022-08-19 06:32 UTC, Geefy commented
File paths are wrong (not right namespace) and Source/Models/MQTTModels/ConnetPackage.h has a spelling error, should be ConnectPackage.h

2022-08-19 08:31 UTC, blackout1471 commented on Source/Models/MQTTModels/ConnetPackage.h
> +			inline const ControlHeader& GetConnectControllHeader() { return m_ControlHeader; }
Fixed it

2022-08-19 08:32 UTC, blackout1471 commented on Source/Models/MQTTModels/ConnetPackage.h
> +			inline void SetConnectControllHeader(const ControlHeader& _controllHeader) { m_ControlHeader = _controllHeader; }
Fixed it

2022-08-19 08:32 UTC, blackout1471 commented on Source/Models/MQTTModels/ConnectFlagType.h
> +		enum ConnectFlagType : int
Fixed

2022-08-19 08:32 UTC, blackout1471 commented on Source/Models/MQTTModels/ConnectVariableHeader.h
> +		public:
fixed.

2022-08-19 08:33 UTC, blackout1471 approved these changes

2022-08-19 08:40 UTC, Geefy approved these changes

2022-08-19 08:40 UTC, merged